### ISSUE TITLE
Mass density of sulfate aerosol

### ISSUE THREAD

**Issue by dan-visioni** [krpetlock/SAI-Ozone-depletion-KP#3]
Reading this part carefully, this needs to be fixed (line 69)

SO₂ to H2SO4 conversion is not just a matter of injection: overall burden is decided by multiple factors.
For daec, I would use values from the model (i.e. see Fig. 2 here https://gmd.copernicus.org/articles/15/8221/2022/#&gid=1&pid=1)
The values you have now for daec (5*e-13) are,I think, a bit too small.
In general, considering here we're talking about the polar stratosphere, probably the total volume calculated above should also only consider 60S-90S.

**Comment by dan-visioni** [comment]
For instance, I calculated the values from that plot for all the years of simulation (2035-2070).
In ug/kg-air, these are (averaged between 60S and 90S, at 100 hPa)

dae_A = [1.76316831368791	3.76816412716447	6.52442931678991	8.53609938612066	10.7140685517671	12.2966859567780	13.7903588023128	15.5519873243085	16.2782985397395	17.5571903258922	18.0413652854746	18.4964897417279	19.7035296135657	20.7486363247361	21.9247465367465	22.6804436501432	23.4822328834513	24.1935057568463	24.9429422009546	26.7418420062779	26.4429281686663	26.4015564317903	27.6797490021677	28.2642410504172	28.8428203501063	29.6018313589000	30.6464248499655	30.6297130120039	32.3670716905531	31.6971458755013	32.5217193032393	32.9857585262976	33.8997627273756	34.7081412104210	        34.7795523872443]

Now with this approach, we would have 
1) more realistic numbers for concentration (can also similarly derive SAD, although numbers should be similar to yours)
2) a test to compare against the ozone depletion actually simulated by CESM, and then a test for modifying the starting date to 2045, verify what number the code gives us, and compare against another set of simulations we have with 2045 start date

**Comment by dan-visioni** [comment]
Ok, I'll confess: I added the values in your code and I get essentially the same value you did!
With CESM values, for year 1, I get 5.73 1e-13. You got 5.56... 
The way how you got it is still sort of wrong in a couple of places, but nonetheless, congrats and I'm ashamed 😆

**Comment by krpetlock** [comment]
Hi Dan,
Sorry for the late reply, -I was finishing another project for one of my
current grad classes that was due yesterday (Fri).
Please let me know which parts I did wrong, -but yes, the 10^-13 difference
does seem to make sense, looking at the units that the model data in
fig. 2 of the source paper you referenced has the SO4 aerosol in, mg/m^2
for the total column, whereas I have my daec value in terms of g/cm^3 to be
consistent with the other parameter units for the calculation as I did it.
Converting:  1m^2 column --> m^3:  /10,000 m column height = 10^-4

m^3 --> cm^3 = 10^-6

   mg --> g  =  10^-3

total order of mag change = - (4+6+3) = 10^-13  (right?)

Using the mid stratospheric volume for just the Antarctic region (60-90S)
also makes sense to me, -just working out (geometrically) how to do the
conversion.
(can't believe I didn't think of that, since we're doing this for the
Antarctic region! :)

I looked at the code changes you made on github for the
streamlining/adaptability.  It's starting to make sense, I just have to
learn more about the linspace function and the syntax for the param
references / call lines.  Great stuff!  I merged your github branch with
mine, as you suggested, -left a comment/message on there wrt the parameters
we're putting in the data file.

Also, just an FYI; for the next few weeks as I'm wrapping up my semester, I
may not be able to work on this as fast as I'd like, but after that I
should be able to
devote more full time to this project.

Kyle

**Comment by krpetlock** [comment]
Yes, makes sense what you said about converting from SO2 precursor to H2SO4, given the evolutionary process from SO2 gas to sulfate aerosol, -I just need to review the chem evolution and get a better understanding of exactly how to apply these factors.  
Also, I thought we were going to add uptake coefficient and SAD values into the param data file. -or will that be the next step?  Kyle
